config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company
  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # after_create_commit ->  { broadcast_prepend_later_to "quotes" }
  # after_update_commit ->  { broadcast_replace_later_to "quotes" }
  # after_destroy_commit ->  { broadcast_remove_to "quotes" }

  # broadcasts_to ->(quote) {"quotes"}, inserts_by: :prepend

  broadcasts_to ->(quote) {[quote.company, "quotes"]}, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  belongs_to :company

  def name
    email.split("@").first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end
  helper_method :current_company
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created" }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated" }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed" }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed" }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flashe__message" data-controller="removals"
    data-action="animationend->removals#remove" >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div>
      <div class="font-semibold text-lg">
        <%= current_company.name %>
      </div>
      <div class="text-base">
        <%= current_user.name %>
      </div>
    </div>
    <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "button" %>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "button" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbo Tutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class= "flex flex-col w-screen h-screen">
      <%= render "layouts/navbar" %>

      <div id="flash" class="flashe">
        <%= render "layouts/flash" %>
      </div>

      <div class="p-6">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<main class="flex flex-col w-full h-full items-center justify-center gap-8">
  <h1 class="title">Quote editor</h1>
  <p>A blazing fast quote editor built with Hotwire</p>
  <% if user_signed_in? %>
    <%= link_to "View quotes", quotes_path, class: "button" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "button" %>
  <% end %>
</main>

app/views/quotes/_form.html.erb
 <%= form_for @quote do |form| %>
  <div class="field-container">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, placeholder: "Enter a quote", autofocus: true, class: "input w-full" %>
  </div>
  <% @quote.errors.full_messages_for(:name).each do |message| %>
    <p class="error-message"><%= message %></p>
  <% end %>

  <div class="flex mt-4 gap-4">
    <%= link_to "Cancel", quotes_path, class: "button" %>
    <%= form.submit class:"button" %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    <%= link_to quote.name, quote_path(quote), data: {turbo_frame: "_top"} %>
    <div class="quote__actions">
      <%= button_to "Delete",
                    quote_path(quote),
                    method: :delete,
                    class: "button" %>
      <%= link_to "Edit",
                  edit_quote_path(quote),
                  class: "button" %>
    </div>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/edit.html.erb
<main class="main">
  <div class="header">
    <%= link_to quotes_path, class: "flex gap-2 items-center" do %>
      <%= image_tag "arrow_back.svg", class: "flex size-6" %>
      <p class="title">Back to quotes</p>
    <% end %>
  </div>
  <hr class="divider">
  <div class="grid w-1/2 p-6 gap-6">
    <h2 class="subtitle">Edit quote</h2>
    <%= render "form" %>
  </div>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from  current_company, "quotes" %>

<main class="main">
  <div class="header">
    <h1 class="title">Quotes</h1>
    <%= link_to "New quote",
                new_quote_path,
                class: "button",
                data: { turbo_frame: "new_quote" } %>
  </div>
  <hr class="divider">

  <%= turbo_frame_tag Quote.new %>

  <%= turbo_frame_tag "quotes", class: "grid gap-4 p-2 mt-4"  do %>
    <%= render @quotes %>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main class="main">
  <div class="header">
    <%= link_to quotes_path, class: "flex gap-2 items-center" do %>
      <%= image_tag "arrow_back.svg", class: "flex size-6" %>
      <p class="title">Back to quotes</p>
    <% end %>
  </div>
  <hr class="divider">
  <div class="grid w-1/2 p-6 gap-6">
    <h1 class="subtitle">New quote</h1>
    <%= turbo_frame_tag @quote do %>
      <div class="p-4">
        <%= render "form", quote: @quote %>
      </div>
    <% end %>
  </div>
</main>

app/views/quotes/show.html.erb
<main class="main">
  <div class="header">
    <%= link_to quotes_path, class: "flex gap-2 items-center" do %>
      <%= image_tag "arrow_back.svg", class: "flex size-6" %>
      <p class="title">Back to quotes</p>
    <% end %>
  </div>
  <hr class="divider">
  <h1 class="p-2 mt-4">
    <%= @quote.name %>
  </h1>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>